import authRouter from "./authRouter.mjs";
import brandRouter from "./brandRouter.mjs";
import budgetRouter from "./budgetRouter.mjs";
import cashierRouter from "./cashierRouter.mjs";
import categoryRouter from "./categoryRouter.mjs";
import clientRouter from "./clientRouter.mjs";
import comissionRouter from "./comissionRouter.mjs";
import deliveryRouter from "./deliveryRouter.mjs";
import expenseRouter from "./expenseRouter.mjs";
import employeeRouter from "./employeeRouter.mjs";
import financial from "./resumeFinancialRouter.mjs";
import homeRouter from "./homeRouter.mjs";
import moreSellRouter from "./moreSellRouter.mjs";
import orderRouter from "./orderRouter.mjs";
import productsRouter from "./productRouter.mjs";
import providerRouter from "./providersRouter.mjs";
import receiveRouter from "./receiveRouter.mjs";
import resumeClientRouter from "./resumeClientRouter.mjs";
import resumeCompanyRouter from "./resumeCompanyRouter.mjs";
import resumeEntryOrdersRouter from "./resumeEntryOrdersRouter.mjs";
import resumeProviderRouter from "./resumeProviderRouter.mjs";
import stockEntryRouter from "./stockEntryRouter.mjs";
import stockOutRouter from "./stockOutRouter.mjs";
import stockRouter from "./stockNowRouter.mjs";
import subCategoryRouter from "./subCategoryRouter.mjs";
import subProductRouter from "./subProductRouter.mjs";
import userRouter from "./userRouter.mjs";
import workPositionRouter from "./workPositionRouter.mjs";
import whatsappRouter from "./whatsappRouter.mjs";


/* eslint import/no-anonymous-default-export: [2, {"allowArrowFunction": true}] */
export default (app, passport) => {
  authRouter(app, passport);
  brandRouter(app);
  budgetRouter(app);
  cashierRouter(app);
  categoryRouter(app);
  clientRouter(app);
  comissionRouter(app);
  deliveryRouter(app);
  employeeRouter(app);
  expenseRouter(app);
  financial(app);
  homeRouter(app);
  moreSellRouter(app);
  orderRouter(app);
  productsRouter(app);
  providerRouter(app);
  receiveRouter(app);
  resumeClientRouter(app);
  resumeCompanyRouter(app);
  resumeEntryOrdersRouter(app);
  resumeProviderRouter(app);
  stockEntryRouter(app);
  stockOutRouter(app);
  stockRouter(app);
  subCategoryRouter(app);
  subProductRouter(app);
  userRouter(app);
  workPositionRouter(app);
  whatsappRouter(app);
};
